#pragma once

// Lifted from 1.7.3 source

#define A_OSUCC 1
#define A_OFAIL 2
#define A_FAIL 3
#define A_SUCC 4
#define A_PASS 5
#define A_DESC 6
#define A_SEX 7
#define A_ODROP 8
#define A_DROP 9
#define A_OKILL 10
#define A_KILL 11
#define A_ASUCC 12
#define A_AFAIL 13
#define A_ADROP 14
#define A_AKILL 15
#define A_USE 16
#define A_CHARGES 17
#define A_RUNOUT 18
#define A_STARTUP 19
#define A_ACLONE 20
#define A_APAY 21
#define A_OPAY 22
#define A_PAY 23
#define A_COST 24
#define A_RAND 25
#define A_LISTEN 26
#define A_AAHEAR 27
#define A_AMHEAR 28
#define A_AHEAR 29
#define A_LAST 30
#define A_QUEUE 31
#define A_IDESC 32
#define A_ENTER 33
#define A_OXENTER 34
#define A_AENTER 35
#define A_ADESC 36
#define A_ODESC 37
#define A_RQUOTA 38
#define A_ACONNECT 39
#define A_ADISCONNECT 40
#define A_LEAVE 41
#define A_ALEAVE 42
#define A_OLEAVE 43
#define A_OENTER 44
#define A_OXLEAVE 45
