function makeCmdsHeader() {
  var fso = new ActiveXObject('Scripting.FileSystemObject');
  var generated_header = fso.CreateTextFile('hdrs/cmds.h', true, false);
  generated_header.WriteLine('/* AUTOGENERATED FILE. DO NOT EDIT! */');
  generated_header.WriteLine('#ifndef CMDS_H');
  generated_header.WriteLine('#define CMDS_H');
  generated_header.WriteLine('#include "command.h"');
  var src_dir = fso.GetFolder('src');
  var src_files = new Enumerator(src_dir.Files);
  for (var i = 0; !src_files.atEnd(); src_files.moveNext()) {
    if (/\.c$/.test(src_files.item().name)) {
      var src_file = fso.OpenTextFile(src_files.item().path);
      while (!src_file.AtEndOfStream) {
        var line = src_file.ReadLine();
        var match = /^\s*COMMAND\(([^)]+)\)/.exec(line);
        if (match) {
          generated_header.WriteLine('COMMAND_PROTO(' + match[1] + ');');
        }
      }
    }
  }
  generated_header.WriteLine('#endif /* CMDS_H */');
}

function makeFunsHeader() {
  var fso = new ActiveXObject('Scripting.FileSystemObject');
  var generated_header = fso.CreateTextFile('hdrs/funs.h', true, false);
  generated_header.WriteLine('/* AUTOGENERATED FILE. DO NOT EDIT! */');
  generated_header.WriteLine('#ifndef FUNS_H');
  generated_header.WriteLine('#define FUNS_H');
  var src_dir = fso.GetFolder('src');
  var src_files = new Enumerator(src_dir.Files);
  for (var i = 0; !src_files.atEnd(); src_files.moveNext()) {
    if (/\.c$/.test(src_files.item().name)) {
      var src_file = fso.OpenTextFile(src_files.item().path);
      while (!src_file.AtEndOfStream) {
        var line = src_file.ReadLine();
        var match = /^\s*FUNCTION\(([^)]+)\)/.exec(line);
        if (match) {
          generated_header.WriteLine('FUNCTION_PROTO(' + match[1] + ');');
        }
      }
    }
  }
  generated_header.WriteLine('#endif /* FUNS_H */');
}

function cdDotDot() {
  var wshShell = WScript.CreateObject('WScript.Shell');
  wshShell.CurrentDirectory = wshShell.CurrentDirectory.substr(
      0,
      wshShell.CurrentDirectory.lastIndexOf('\\'));
}

cdDotDot();
cdDotDot();
makeCmdsHeader();
makeFunsHeader();
