/* PennMUSH config.h. Autogenerated by ./configure */

#ifndef __CONFIG_H
#define __CONFIG_H

/* Headers */

#undef I_ARPA_INET

#undef I_ARPA_NAMESER

#define I_FCNTL

#undef I_FLOATINGPOINT

#undef I_LIBINTL

#define I_MALLOC

#undef I_NETDB

#undef I_NETINET_IN

#undef I_NETINET_TCP

#undef HAVE_STDINT_H

#undef I_SYS_ERRNO

#undef I_SYS_FILE

#undef I_SYS_IN

#undef I_SYS_MMAN

 #undef I_SYS_PAGE

#undef I_SYS_PARAM

#undef I_SYS_SOCKET

#define I_SYS_STAT

#undef I_SYS_TIME

#undef TIME_WITH_SYS_TIME

#define I_SYS_TYPES

#undef HAVE_UNISTD_H

#ifdef HAVE_UNISTD_H
#define I_UNISTD
#endif

#undef HAVE_SYS_WAIT_H

#ifdef HAVE_SYS_WAIT_H
#define I_SYS_WAIT
#endif

#undef HAVE_IEEEFP_H

#undef HAVE_SYS_UN_H

#undef HAVE_SYS_EVENT_H

/* C99ish headers. The first two are really really nice to have. */

#undef HAVE_STDINT_H

#undef HAVE_INTTYPES_H

#undef HAVE_STDBOOL_H

/* Libraries */

#undef HAVE_MYSQL

#ifdef HAVE_MYSQL
#define HAS_MYSQL
#endif

#undef HAVE_POSTGRESQL

#undef HAVE_SQLITE3

#undef HAVE_SSL

#ifdef HAVE_SSL
#define HAS_OPENSSL
#endif

/* Types */

#undef HAVE__BOOL

#define socklen_t unsigned long

#define uint8_t unsigned __int8

#define uint16_t unsigned __int16

#define int32_t  __int32

#define uint32_t unsigned __int32

#define int64_t __int64

#define uint64_t unsigned __int64

#define intmax_t __int64
#define uintmax_t unsigned __int64

#define pid_t unsigned long

/* 4 */
#define SIZEOF_INT 4

/* 4 or 8 */
#define SIZEOF_LONG 4

/* 0 if no 64-bit type (We shouldn't be seeing that case) or 8. See below. */
#define SIZEOF_INT64_T 8

/* 8 on most modern CPUs Penn will be used on. They either have  64-bit 
* words (amd64, sparc64, powerpc64) or support an extended 64-bit type (i386, 
* powerpc32) */
#define SIZEOF_INTMAX_T 8

#define SIZEOF_TIME_T 4

/* 4 or 8 */
#define SIZEOF_VOID_P 4

/* Taken from autoconf manual */
#if HAVE_STDBOOL_H
# include <stdbool.h>
#else
# if ! HAVE__BOOL
#  ifdef __cplusplus
typedef bool _Bool;
#  else
#   define _Bool signed char
#  endif
# endif
# define bool _Bool
# define false 0
# define true 1
# define __bool_true_false_are_defined 1
#endif

typedef void* Malloc_t;
typedef void Free_t;

/* Functions */
#undef HAS_BINDTEXTDOMAIN

#undef HAVE_CBRT

#undef HAS_CRYPT

#undef HAS_FPSETMASK

#undef HAS_FPSETROUND

#undef HAS_GAI_STRERROR

#undef HAS_GETADDRINFO

#undef HAS_GETDATE

#undef HAS_GETHOSTBYNAME2

#undef HAS_GETNAMEINFO

#undef HAS_GETPAGESIZE

#undef HAS_GETRLIMIT

#undef HAS_GETRUSAGE

#undef HAS_GETTEXT

#undef HAS_INET_PTON

#undef HAS_ITIMER

#define HAS_SETLOCALE

#undef HAVE_FORK

#undef HAVE_SETPGRP

#undef SETPGRP_VOID

#undef HAVE_GETUID

#undef HAVE_GETEUID

#undef HAVE_SETEUID

#undef HAVE_GETPRIORITY

#undef HAVE_SETPRIORITY

#undef HAVE_SIGACTION

#undef HAVE_SIGPROCMASK

#undef HAVE_SNPRINTF

#undef HAS_SOCKETPAIR

#undef HAVE_STRCASECMP

/* Various Windows (And maybe others?) string functions  start with _str */

#define HAVE__STRICMP

#define HAVE__STRNICMP

#define HAVE__STRICOLL

#define HAVE__STRNCOLL

#define HAVE__STRNICOLL

#define HAVE__SNPRINTF

#define HAVE__VSNPRINTF

#define HAVE__VSNPRINTF_S

#define HAS_STRDUP

#define HAVE_STRCOLL

#define HAS_STRXFRM

#undef HAS_SYSCONF

#undef HAS_TEXTDOMAIN

#undef HAS_VSNPRINTF

#undef HAS_WAITPID

#undef HAVE_WAIT3

#undef HAVE_WAIT

#define UNION_WAIT

/* Variables and defines */

#define HAVE_H_ERRNO

#undef HAVE_SIGCHLD

#undef HAVE_SIGCLD

/* Files */

#undef HAS_DEV_URANDOM

/* Misc. */

#undef HAVE_SOCKADDR_IN6

#undef FORCE_IPV4

#define DONT_TRANSLATE

#undef HAVE_UPTIME

#undef UPTIME

#undef HAVE_SENDMAIL

#undef SENDMAIL

#define HAVE_SAFE_TOUPPER

/* Optional language features */
#define restrict
#undef inline
#ifndef _SSIZE_T_DEFINED
#ifdef  _WIN64
typedef __int64 ssize_t;
#else
typedef int ssize_t;
#endif
#define _SSIZE_T_DEFINED
#endif

#ifdef _MSC_VER
#define WIN32_CDECL __cdecl
#else
#define WIN32_CDECL
#endif

#undef HAVE___ATTRIBUTE__

#ifndef HAVE___ATTRIBUTE__
#define __attribute__(x)
#endif

#undef GCC_MALLOC_CALL

/* TODO: Change in source */
#define RESTRICT

#endif /* __CONFIG_H */
